import type { NextPage } from 'next'
import Head from 'next/head'
import React, { useState } from 'react'

const Home: NextPage = () => {
    const [roomID, setRoomID] = useState<string>('')

    const handleRoomIDChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        setRoomID(e.currentTarget.value)
    }

    return (
        <div className="bg-gray-100 min-h-screen w-screen">
            <Head>
                <title>Video App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="max-w-3xl mx-auto py-28 text-center px-4 sm:px-6 lg:py-40 lg:px-8 lg:flex-row lg:items-center lg:justify-between">
                <h1 className="text-2xl font-extrabold tracking-tight text-gray-900 sm:text-4xl">
                    <span className="block">Join a Meeting</span>
                    <span className="block">or Start Create New</span>
                </h1>
                <div className="mt-8 flex-row lg:mt-0 lg:flex-shrink-0">
                    <div className="inline-flex rounded-md shadow">
                        <a
                            href="#"
                            className="inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-red-600 hover:bg-red-700"
                        >
                            Create new Room
                        </a>
                    </div>

                    <div className="mt-5 lg:ml-5 inline-flex rounded-md shadow lg:mt-10">
                        <label htmlFor="room-id" className="sr-only">
                            Room ID
                        </label>
                        <input
                            value={roomID}
                            onChange={handleRoomIDChange}
                            aria-label="room-input"
                            id="room-id"
                            name="room"
                            type="room"
                            autoComplete="room"
                            required
                            className="appearance-none rounded-none relative block w-36 px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                            placeholder="Room ID"
                        />
                        <a
                            href="#"
                            className="inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-red-600 bg-white hover:bg-indigo-50"
                        >
                            Join a Meeting
                        </a>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Home
